
/*
 * GET home page.
 */

// include schema to save records to database
var FlightSchema = require('../schemas/flights');

module.exports = function(flights) {
	var flight = require('../flight');

	for(var number in flights) {
		flights[number] = flight(flights[number]);
	}

	var functions = {};

	functions.flight = function(req, res){
		var number = req.param('number');
		
		if (typeof flights[number] === 'undefined') {
			res.status(404).json({status: 'error'});
		} else {
			res.json(flights[number].getInformation());
		}
	};

	functions.arrived = function(req, res) {
		var number = req.param('number');
		
		if (typeof flights[number] === 'undefined') {
			res.status(404).json({status: 'error'});
		} else {
			
			flights[number].triggerArrive();
			
			// save timestamp generated by triggerArrive() method to database
			var record = new FlightSchema(
				flights[number].getInformation()
			);
			
			record.save(function(err) {
				if (err) {
					console.log(err);
					res.status(500).json({status: 'failure'});
				} else {
					res.json({status: 'success'});
				}
			});
			
			res.json({status: 'done'});
		}
	};

	functions.list = function(req, res) {
		res.render('list', {
			title: 'All Flights', 
			flights: flights});
	};
	
	// route handler for arrivals
	functions.arrivals = function(req, res) {
		FlightSchema.find()
		.setOptions({sort: 'actualArrive'})
		.exec(function(err, arrivals) {
			if (err) {
				console.log(err);
				res.status(500).json({status: 'failure'});
			} else {
				res.render('arrivals', {
					title: 'Arrivals',
					arrivals: arrivals
				});
			}
		});
	};

	return functions;
};
